Fix regression and restore connectivity when UDPMuxDefault and NAT1To1IPs are used
pion/ice pull request #550
Opened 2023-04-12 17:20 UTC by aler9

#### Description

PR #496 added a mechanism to close connections of duplicate candidates and avoid memory leaks. When UDPMuxDefault and NAT1To1IPs are used together, candidates may share the same connection, and candidates may be equal, since their IPs are overridden by the one specified in NAT1To1IPs. When a duplicate candidate is found, its connection is closed, making impossible to use any other candidate that shares the same connection.

This PR fixes the issue as it prevents duplicate candidates from creating connections and getting their connection closed.

#### Reference issue

2023-04-12 17:27 UTC, stv0g requested changes

2023-04-12 17:27 UTC, stv0g commented on gather.go
> +		// detect a duplicate candidate before calling addCandidate().
Please start comments with an uppercase letter.

2023-04-12 17:27 UTC, stv0g commented on gather_test.go
> +// Assert that candidates are given and connections are valid
Please start function comments in the form:

```go
// TestUDPMuxDefaultWithNAT1To1IPsUsage asserts that ...
```

2023-04-12 17:28 UTC, stv0g commented
Thanks @aler9! Thats great :) I have two smaller comments on your PR.

And, I've noticed that the PR is based on an outdated `master` branch.
Could you rebase your changes on the latest `master`?

Thanks a lot :)

2023-04-12 17:29 UTC, stv0g commented
I also assume that this will fix https://github.com/pion/ice/issues/505?

@aler9 could you confirm this?

2023-04-12 17:41 UTC, aler9 commented
Hello @stv0g, i have applied all the requested changes and i can confirm that this fixes #505. Furthermore, the PR adds a unit test with the exact use case (UDPDefaultMux + NAT1To1).

The question is that UDPMux is used in two ways:

* with `NewMultiUDPMuxFromPort` like [livekit](https://github.com/livekit/livekit) and @cnderrauber do. This caused the memory leak that was solved with #496
* with `NewUDPMuxDefault` like [mediamtx](https://github.com/aler9/mediamtx) and i do. This has the advantage of not having to scan interfaces manually, but stopped working after #496

Personally i don't have a preference and it's not my role to decide, but i'd like for both methods to continue working in order not to break existing code.

2023-04-12 17:44 UTC, stv0g approved these changes

2023-04-12 17:46 UTC, stv0g commented
Thanks @aler9,

It looks good now. We can ignore the failing CI tests for Go 1.18.

I will @cnderrauber some time to also review the change.
But from my side, we could merge it 👍

2023-04-14 07:00 UTC, cnderrauber reviewed
Thanks for improving this!

2023-04-14 14:29 UTC, aler9 commented on gather.go
> +		configs[hostConfig] = struct{}{}
thanks, i moved the line after addCandidate()

2023-04-14 15:43 UTC, cnderrauber approved these changes

2023-04-14 21:15 UTC, merged